/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'si' at '16/03/31 22:59' with Gradle 2.9
 *
 * @author si, @date 16/03/31 22:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
